
export interface SurveyEntry {
  id: string;
  timestamp: string;
  latitude: string;
  longitude: string;
  // Section 01
  date_enquete: string;
  region: string;
  departement: string;
  arrondissement: string;
  village: string;
  is_pecheur: string;
  is_marineur: string;
  nom_prenom: string;
  telephone: string;
  num_enregistrement: string;
  // Section 02
  // tranche_age: string;
  age: string;
  sexe: string;
  situation_matrimoniale: string;
  enfants_charge: string;
  niveau_etude: string;
  religion: string;
  // region_origine: string;
  activite_principale: string;
  activite_principale_autre: string; // New field
  activite_secondaire: string;
  activite_secondaire_autre: string;
  experience: string;
  motif_activite: string;
  motif_activite_autre: string;
  // Section 03
  distinguer_machoiron: string;
  nb_especes_pechees: string;
  distinction_methode: string;
  // nom_local_existe: string;
  // noms_locaux: string;
  nom_maternelle_A: string;
  nom_maternelle_B: string;
  nom_maternelle_C: string;
  espece_plus_pechee: string;
  espece_preferee: string;
  espece_plus_grande: string;
  poids_max_A: string;
  poids_max_B: string;
  poids_max_C: string;
  annee_max_A: string;
  annee_max_B: string;
  annee_max_C: string;
  poids_max_2025_A: string;
  poids_max_2025_B: string;
  poids_max_2025_C: string;
  taille_min_2025_A: string;
  taille_min_2025_B: string;
  taille_min_2025_C: string;
  evolution_quantite_A: string;
  evolution_quantite_B: string;
  evolution_quantite_C: string;
  periode_abondante_A: string;
  periode_abondante_B: string;
  periode_abondante_C: string;
  lieu_peche_A: string;
  lieu_peche_B: string;
  lieu_peche_C: string;
  difficultes_capture: string;
  engins_A: string;
  engins_B: string;
  engins_C: string;
  engin_adapte_A: string;
  engin_adapte_B: string;
  engin_adapte_C: string;
  // Section 04
  acheteurs_A: string;
  acheteurs_B: string;
  acheteurs_C: string;
  lieu_achat: string;
  motif_achat: string;
  lieu_achat_autre: string;
  quantites_max: string;
  quantites_max_oui: string;
  poids_prise_petit: string;
  poids_prise_gros: string;
  etat_vente_A: string;
  etat_vente_B: string;
  etat_vente_C: string;
  methode_mesure_A: string;
  methode_mesure_B: string;
  methode_mesure_C: string;
  periode_prix_eleve: string;
  raison_periode_prix_eleve: string;
  prix_periode_A: string;
  prix_periode_B: string;
  prix_periode_C: string;
  prix_max_saison_A: string;
  prix_max_saison_B: string;
  prix_max_saison_C: string;
  difficultes_vente: string;
}
